version: '3.6'

services: 
  postgres:
    image: postgres
    restart: always
    environment: 
      POSTGRES_USER: root
      PORTGRES_PASSWORD: mercafacil
      POSTGRES_DB: pgmercafacil
      POSTGRES_HOST_AUTH_METHOD: trust
    ports: 
     - "5434:5432"
    volumes: 
      - ./scripts/postgres:/docker-entrypoint-initdb.d/
  mysql-dev:
    image: mysql:8.0.2
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mercafacil
      MYSQL_DATABASE: mysqlmercafacil
    ports: 
      - "3308:3306"
    volumes:
      - ./scripts/mysql:/docker-entrypoint-initdb.d/
